Support for IPv4 and IPv6
serge-chat/serge pull request #1055
Opened 2024-01-13 18:32 UTC by Smartappli

2024-01-14 14:08 UTC, gaby commented
@Smartappli We need to migrate to hypercorn, else we will be running 2 servers at the same time

2024-01-14 18:41 UTC, Smartappli commented
> @Smartappli We need to migrate to hypercorn, else we will be running 2 servers at the same time.
> 
> See here: [encode/uvicorn#1529 (reply in thread)](https://github.com/encode/uvicorn/discussions/1529#discussioncomment-7264527)

thanks :)

2024-01-15 17:18 UTC, gaby requested changes

2024-01-15 17:18 UTC, gaby commented on scripts/deploy.sh
> +	if [ "$SERGE_GPU_SUPPORT" = false ]; then
Why is this here?

2024-01-15 17:18 UTC, gaby commented on scripts/serge.env
> +SERGE_GPU_SUPPORT=false
Why is this here?

2024-01-15 17:18 UTC, gaby commented on scripts/dev.sh
> +	if [ "$SERGE_GPU_SUPPORT" = false ]; then
Same here

2024-01-16 18:10 UTC, gaby requested changes

2024-01-16 18:10 UTC, gaby commented on scripts/deploy.sh
> +hypercorn src.serge.main:app --bind 0.0.0.0:8008 --bind [::]:8008 || {
This is forcing ipv6 to everyone. It needs to be an env option.

`SERGE_ENABLE_IPV6`

2024-01-16 18:10 UTC, gaby commented on scripts/dev.sh
> +hypercorn src.serge.main:api_app --reload --bind 0.0.0.0:9124 --bind [::]:9124 --root-path /api/ || {
Same here as above

2024-01-18 04:08 UTC, gaby commented
@Smartappli Can you take a look at the merge conflicts

2024-01-18 13:29 UTC, gaby approved these changes

2024-01-18 13:31 UTC, merged