Support of GPUs
serge-chat/serge pull request #999
Opened 2023-12-20 01:11 UTC by Smartappli

2023-12-27 14:20 UTC, gaby requested changes

2023-12-27 14:20 UTC, gaby commented on docker/Dockerfile.dev
> +    && apt-get upgrade -y \
Remove this

2023-12-27 14:20 UTC, gaby commented on docker/Dockerfile
> +    && apt-get upgrade -y \
Remove this

2023-12-27 14:20 UTC, gaby commented on docker-compose.gpu.yml
> +services:
This compose is not using gpus

2023-12-27 14:20 UTC, gaby commented on docker/Dockerfile.gpu
> +    && apt-get upgrade -y \
Remove

2023-12-27 14:44 UTC, Smartappli commented on docker-compose.gpu.yml
> +services:
What exactly do you want me to change?

2023-12-27 14:44 UTC, Smartappli commented on docker/Dockerfile
> +    && apt-get upgrade -y \
done

2023-12-27 14:44 UTC, Smartappli commented on docker/Dockerfile.gpu
> +    && apt-get upgrade -y \
done

2023-12-27 14:45 UTC, Smartappli commented on docker/Dockerfile.dev
> +    && apt-get upgrade -y \
done

2023-12-27 14:45 UTC, Smartappli commented
Can you help me with the docker compose gpu I don't know what to do.

2023-12-27 15:32 UTC, gaby commented
@Smartappli Can you fix the merge conflict, will merge after that. Thanks! 💪

2023-12-27 16:14 UTC, Smartappli commented
How do I resolve the conflict?

2023-12-27 21:19 UTC, Smartappli commented
> @Smartappli Can you fix the merge conflict, will merge after that. Thanks! s💪

@gaby done

2023-12-27 22:34 UTC, gaby commented
@Smartappli CI is failing

2023-12-27 23:27 UTC, kraoc commented
I tried and made some changes:

**Dockerfile.gpu**
Before ```ENV NODE_ENV='production'``` need to add ```FROM debian:bookworm```

Also need to update all **pip install** to **pip install --break-system-packages** everywhere.

Image build is now ok but Serge still not seem to use gpu.

2023-12-27 23:29 UTC, gaby commented
@kraoc llama.cpp has to be told to use gpu, everything is setup not to. This is just prep-work for the CI/project structure before adding gpu.

Not everyone has a gpu so Serge has to support all 3 cases: cpu, gpu, cpu/gpu.

2023-12-28 00:43 UTC, gaby commented on docker/Dockerfile.gpu
> +    && pip install --break-system-packages everywhere \
Never seen this before

2023-12-28 00:44 UTC, gaby commented on docker/Dockerfile.gpu
> +FROM debian:bookworm
This will remove all the previous stuff, including CUDA

2024-01-02 04:02 UTC, gaby commented
@Smartappli Any updates on this?

2024-01-03 12:51 UTC, closed without merging